name: Testing CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: '0+unh(kl4@na%(y!4lk-12j6@&s@7a+q#1-9nfzlk0hd34t!fb'
        DEBUG: 'True'
        DATABASE_URL: 'sqlite:///:memory:'
      run: |
        python manage.py collectstatic --noinput
        python manage.py test
